-- schema.sql
-- ✅ Добавляем IF NOT EXISTS ко всем CREATE TABLE

CREATE TABLE IF NOT EXISTS USERS (
                                     USER_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     NAME VARCHAR(255) NOT NULL,
                                     EMAIL VARCHAR(255) NOT NULL UNIQUE,
                                     LOGIN VARCHAR(255) NOT NULL UNIQUE,
                                     BIRTHDAY DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS GENRE_TYPE (
                                          GENRE_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          NAME VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS MPA_TYPE (
                                        RATING_MPA_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        NAME VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS FILMS (
                                     FILM_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     NAME VARCHAR(255) NOT NULL,
                                     DESCRIPTION VARCHAR(1000),
                                     RELEASE_DATE DATE,
                                     DURATION INTEGER NOT NULL,
                                     GENRE_ID INTEGER,
                                     MPA_ID INTEGER
);

CREATE TABLE IF NOT EXISTS FILM_GENRES (
                                           FILM_ID INTEGER NOT NULL,
                                           GENRE_ID INTEGER NOT NULL,
                                           PRIMARY KEY (FILM_ID, GENRE_ID)
);

CREATE TABLE IF NOT EXISTS FRIENDS (
                                       USER_ID INTEGER NOT NULL,
                                       FRIEND_ID INTEGER NOT NULL,
                                       PRIMARY KEY (USER_ID, FRIEND_ID)
);

CREATE TABLE IF NOT EXISTS LIKES (
                                     USER_ID INTEGER NOT NULL,
                                     FILM_ID INTEGER NOT NULL,
                                     PRIMARY KEY (USER_ID, FILM_ID)
);

CREATE TABLE IF NOT EXISTS POPULAR_USERS (
                                             USER_ID INTEGER NOT NULL PRIMARY KEY,
                                             FRIENDS_COUNT INTEGER DEFAULT 0
);

-- Добавляем жанры (только если их нет)
MERGE INTO GENRE_TYPE (GENRE_ID, NAME) VALUES
                                           (1, 'Комедия'),
                                           (2, 'Драма'),
                                           (3, 'Мультфильм'),
                                           (4, 'Триллер'),
                                           (5, 'Документальный'),
                                           (6, 'Боевик');

-- Добавляем MPA рейтинги
MERGE INTO MPA_TYPE (RATING_MPA_ID, NAME) VALUES
                                              (1, 'G'),
                                              (2, 'PG'),
                                              (3, 'PG-13'),
                                              (4, 'R'),
                                              (5, 'NC-17');